//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WolfClan.SoliHub.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Chat
    {
        public long Id { get; set; }
        public string UserID { get; set; }
        public string PartnerId { get; set; }
        public string BeginDate { get; set; }
        public string EndDate { get; set; }
        public string UserIp { get; set; }
        public string PartnerIp { get; set; }
    }
}
