//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WolfClan.SoliHub.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_User
    {
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public byte[] Password { get; set; }
        public string Address { get; set; }
        public System.DateTime Birthday { get; set; }
        public int Gender { get; set; }
        public int Language { get; set; }
        public string Phone { get; set; }
        public byte[] ProfilePic { get; set; }
        public System.DateTime RegDate { get; set; }
        public string Share_Code { get; set; }
        public int Status { get; set; }
    }
}
